resources:
  containers:
  - container: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
    env:
      ACCEPT_EULA: Y
      SA_PASSWORD: $(saPassword)
      MSSQL_PID: Express
    ports: 
      - 1433:1433
    options: --name mssql

stages:
- stage: DBBuild  
  jobs:
  - job: unit_test_db_mssql
    # condition: eq('${{ variables.runDbTests }}', 'true')
    continueOnError: true
    pool:
      vmImage: 'ubuntu-16.04'
    services:
      mssql: mssql
    steps:
    - task: PowerShell@2
      displayName: 'Sleep'
      inputs:
        targetType: 'inline'
        script: |
          start-sleep -s 60

    - task: Bash@3
      displayName: "List Environment Variables"
      inputs:
        targetType: 'inline'
        script: 'env | sort'
    - task: CmdLine@2
      displayName: "List docker images"
      inputs:
        script: 'docker ps -all'
    - task: CmdLine@2
      displayName: "Show docker logs"
      inputs:
        script: 'docker logs mssql'
    - task: CmdLine@2
      displayName: "Connect to SQLServer and Query version" 
      inputs:
        script: 'sqlcmd -S localhost -d master -U sa -P $(saPassword) -Q "SELECT @@version;"'
    - task: Bash@3
      displayName: "Update apt-get"
      inputs:
        script: 'apt-get update \
apt-get install unzip -y'

