# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
resources:
  containers:
  - container: mssql2017
    image: mcr.microsoft.com/mssql/server:2017-latest
    env:
      ACCEPT_EULA: Y
      SA_PASSWORD: $(saPassword)
      MSSQL_PID: Express
    ports: 
      - 1433:1433
    options: --name mssql2017
  - container: mssql2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    env:
      ACCEPT_EULA: Y
      SA_PASSWORD: $(saPassword)
      MSSQL_PID: Express
    ports: 
      - 1433:1433
    options: --name mssql2019
  pipelines:
    - pipeline: 1Basic
      source: SQLPioneer.PipelineDemo.1Basic

trigger:
  paths:
    include:
      - 2Container/*
    exclude:
      - 1Basic/*
variables:
- name: DAC
  value: SchoolProject\SchoolProject.dacpac
- name: DBNAME
  value: SchoolProject
- name: debug
  value: true
stages:
- stage: deployToContainer
  jobs:
  - job: DeployDacpacInContainer
    # condition: eq('${{ variables.runDbTests }}', 'true')
    strategy:
     matrix:
       mssql2017:
         mssqlService: mssql2017
       mssql2019:
         mssqlService: mssql2019
    continueOnError: true
    pool:
      vmImage: 'ubuntu-latest'
    services:
      mssql: $[ variables['mssqlService'] ]
    steps:
    - download: 1Basic
    - task: Bash@3
      displayName: "Install sqlpackage"
      inputs:
        targetType: 'inline'
        script: |
          wget -progress=bar:force -q -O sqlpackage.zip https://go.microsoft.com/fwlink/?linkid=873926
          unzip -qq sqlpackage.zip -d /opt/sqlpackage 
          chmod +x /opt/sqlpackage/sqlpackage
    - task: Bash@3
      displayName: "List Environment Variables"
      inputs:
        targetType: 'inline'
        script: 'env | sort'
    - task: CmdLine@2
      displayName: "List docker images"
      inputs:
        script: 'docker ps -all'
    - task: PowerShell@2
      displayName: 'Sleep'
      inputs:
        targetType: 'inline'
        script: |
          dir -s
          start-sleep -s 60
    - task: CmdLine@2
      displayName: "Show docker logs"
      inputs:
        script: 'docker logs mssql2017'
    - task: CmdLine@2
      displayName: "Connect to SQLServer and Query version" 
      inputs:
        script: 'sqlcmd -S localhost -d master -U sa -P $(saPassword) -Q "SELECT @@version;"'
    - task: Bash@3
      displayName: "publish dacpac to container"
      inputs:
        targetType: 'inline'
        script: |
          ( /opt/mssql/bin/sqlservr & ) | grep -q "Service Broker manager has started"
          /opt/sqlpackage/sqlpackage /sf:$(Pipeline.Workspace)/1Basic/SchoolProjectDB/SchoolProject.dacpac /a:Publish /tsn:localhost /tdn:$(DBNAME) /tu:sa /tp:$(saPassword)
    - task: CmdLine@2
      displayName: "Connect to SQLServer and Query SchoolProject DB" 
      inputs:
        script: 'sqlcmd -S localhost -d SchoolProject -U sa -P $(saPassword) -Q "SELECT @@ServerName as ServerName, DB_NAME() AS CurrentDB;"' 
